---
title: "R Notebook"
output: html_notebook
editor_options: 
  chunk_output_type: console
---

```{r}
install.packages(c("dplyr", "ggplot2"))
library(dplyr)
library(ggplot2)
library(readr)
library(scales)
autotrader_df_ioniq <- read_csv("C:/Users/mjgva/Downloads/autotrader-df-ioniq.csv", 
    col_types = cols(year = col_character(), 
        engine = col_character()))

autotrader_df_corolla <- read_csv("C:/Users/mjgva/Downloads/autotrader-df-corolla.csv", 
    col_types = cols(year = col_character(), 
        engine = col_character()))


```

```{r}

str(autotrader_df_ioniq)

autotrader_df_ioniq %>%
    filter(!is.na(year)) %>% 
    ggplot(aes(y = price, x = mileage, color = year)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +  # Add a trend line
    facet_wrap( ~ fuel, ncol = 3) +
    scale_y_continuous(labels = comma, name = "Price (GBP)") +
    scale_x_continuous(labels = comma, name = "Mileage (miles)") +
    labs(title = "Hyundai Ioniq price by mileage, year and fuel type")

autotrader_df_ioniq %>%
    filter(!is.na(year),
           fuel == "Petrol Hybrid") %>% 
    ggplot(aes(y = price, x = mileage, color = year)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +  # Add a trend line
    facet_wrap( ~ year, ncol = 5) +
    scale_y_continuous(labels = comma, name = "Price (GBP)") +
    scale_x_continuous(labels = comma, name = "Mileage (miles)") +
    labs(title = "Hyundai Ioniq (HEV) price by mileage and year")

autotrader_df_ioniq %>%
    filter(!is.na(year),
           fuel == "Petrol Hybrid") %>%
    ggplot(aes(y = price, x = mileage, color = year)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +  # Add a trend line
    facet_wrap( ~ owners, ncol = 5) +
    scale_y_continuous(labels = comma, name = "Price (GBP)") +
    scale_x_continuous(labels = comma, name = "Mileage (miles)") +
    labs(title = "Hyundai Ioniq price by mileage, year and owners")
```

```{r}
autotrader_df_corolla %>%
    filter(!is.na(year),
           !is.na(fuel)) %>% 
    ggplot(aes(y = price, x = mileage, color = year)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +  # Add a trend line
    facet_wrap( ~ fuel, ncol = 2) +
    scale_y_continuous(labels = comma, name = "Price (GBP)") +
    scale_x_continuous(labels = comma, name = "Mileage (miles)") +
    labs(title = "Toyota Corolla price by mileage, year and fuel type")

autotrader_df_corolla %>%
    filter(!is.na(year),
           !is.na(fuel),
           fuel == "Petrol Hybrid") %>%
    ggplot(aes(y = price, x = mileage, color = year)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +  # Add a trend line
    facet_wrap( ~ year, ncol = 4) +
    scale_y_continuous(labels = comma, name = "Price (GBP)") +
    scale_x_continuous(labels = comma, name = "Mileage (miles)") +
    labs(title = "Toyota Corolla price by mileage and year")

autotrader_df_corolla %>%
    filter(!is.na(year),
           fuel == "Petrol Hybrid") %>%
    ggplot(aes(y = price, x = mileage, color = year)) +
    geom_point() +
    geom_smooth(method = "lm", se = FALSE) +  # Add a trend line
    facet_wrap( ~ owners, ncol = 5) +
    scale_y_continuous(labels = comma, name = "Price (GBP)") +
    scale_x_continuous(labels = comma, name = "Mileage (miles)") +
    labs(title = "Toyota Corolla price by mileage, year and owners")
```

